version: '3.8'  # Указываем версию формата Docker Compose. 3.8 — это одна из стабильных версий.

services:  # Здесь перечисляются все сервисы, которые будут запускаться в контейнерах.
  db:  # Описание сервиса для базы данных PostgreSQL
    image: postgres:13  # Используется официальный образ PostgreSQL версии 13
    container_name: postgres_db  # Название контейнера для этого сервиса
    environment:  # Задание переменных окружения для контейнера
      POSTGRES_DB: projekt2  # Создание базы данных с именем "projekt2"
      POSTGRES_USER: projekt2_user  # Имя пользователя базы данных
      POSTGRES_PASSWORD: 8$PpT!wq2Z#iKmQxR7^VjL0l  # Пароль пользователя для базы данных
    ports:  # Проброс портов, чтобы контейнер был доступен извне
      - "5432:5432"  # Пробрасываем порт 5432 контейнера (по умолчанию PostgreSQL) на хост-машину
    volumes:  # Монтируем том для хранения данных PostgreSQL
      - postgres_data:/var/lib/postgresql/data  # Данные базы данных будут храниться в томе "postgres_data", чтобы сохраняться при перезапуске контейнера

  app:  # Описание сервиса для приложения
    build: .  # Указание, что контейнер для этого сервиса нужно собирать из текущей директории (где находится Dockerfile)
    container_name: library_app  # Название контейнера для приложения
    depends_on:  # Указываем зависимость: этот сервис будет запускаться после того, как база данных будет готова
      - db  # Приложение зависит от сервиса базы данных "db"
    environment:  # Задание переменных окружения для контейнера
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projekt2  # URL для подключения к базе данных PostgreSQL, где "db" — это имя контейнера с базой данных
      SPRING_DATASOURCE_USERNAME: projekt2_user  # Имя пользователя для подключения к базе данных
      SPRING_DATASOURCE_PASSWORD: 8$PpT!wq2Z#iKmQxR7^VjL0l  # Пароль пользователя для подключения к базе данных
    ports:  # Проброс портов для приложения
      - "8080:8080"  # Приложение будет доступно на порту 8080

volumes:  # Определение томов, которые будут использоваться сервисами
  postgres_data:  # Это том для хранения данных базы данных PostgreSQL
